services:
  # api:
  #   container_name: api-dev
  #   build:
  #     context: .
  #     dockerfile: ./apps/api/Dockerfile.dev
  #   env_file:
  #     - ./apps/api/.env
  #   ports:
  #     - '3001:3001'
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/apps/api/node_modules
  # web:
  #   container_name: web-dev
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: pnpm --filter web dev
  #   environment:
  #     - NODE_ENV=development
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler-pro
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - backend
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_DB=schedulerpro
      - ADMINER_DEFAULT_USER=admin
      - ADMINER_DEFAULT_PASSWORD=admin123

volumes:
  postgres_data:

networks:
  backend:
