import {
  IconAlertTriangle,
  IconArrowRight,
  IconBrandAsana,
  IconBrandGithub,
  IconBrandGoogleFilled,
  IconBrandOffice,
  IconBrandTwitter,
  IconBrandWhatsappFilled,
  IconBrandWindowsFilled,
  IconCalendarEvent,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconDesk,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconHome,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUsersGroup,
  IconUserX,
  IconX
} from '@tabler/icons-react'

export type Icon = React.ComponentType<IconProps>

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  tasks: IconBrandAsana,
  usersGroup: IconUsersGroup,
  events: IconCalendarEvent,
  home: IconHome,
  whatsapp: IconBrandWhatsappFilled,
  google: IconBrandGoogleFilled,
  microsoft: IconBrandWindowsFilled,
  office: IconBrandOffice,
  desk: IconDesk
}
